[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nanuqfi_allocator = "2QtJ5kmxLuW2jYCFpJMtzZ7PCnKdoMwkeueYoDUi5z5P"
nanuqfi_adaptor = "HsNnmuB18pA2U24K4Stc1yan67Cx96gmvGRqBUqRFWwY"
mock_ranger_vault = "FCW6LsSvGAv3UdLixCkm4vygifxR1sVBonuserqFe9Fm"

[programs.devnet]
nanuqfi_allocator = "2QtJ5kmxLuW2jYCFpJMtzZ7PCnKdoMwkeueYoDUi5z5P"
nanuqfi_adaptor = "HsNnmuB18pA2U24K4Stc1yan67Cx96gmvGRqBUqRFWwY"
mock_ranger_vault = "FCW6LsSvGAv3UdLixCkm4vygifxR1sVBonuserqFe9Fm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/Documents/secret/solana-devnet.json"

[scripts]
test = "pnpm vitest run"
