[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nanuqfi_allocator = "CDhkMBnc43wJQyVaSrreXk2ojvQvZMWrAWNBLSjaRJxq"

[programs.devnet]
nanuqfi_allocator = "CDhkMBnc43wJQyVaSrreXk2ojvQvZMWrAWNBLSjaRJxq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/Documents/secret/solana-devnet.json"

[scripts]
test = "pnpm vitest run"
